### ISSUE TITLE
Feature request - cover the missing settings

### ISSUE THREAD

**Issue by canope-25** [DonaldChung-HK/z2m-moes-trv-801-converter#1]
Hi,

First of all thank you for the js template !

Seems to cover almost everything beside the hysteresis that will be used for the eco mode.

I would like to ask you if it's feasible to also support it ?

Ideally I would also like to know is the battery voltage can also be fetched / parsed .

Thank you in advance 

![image](https://github.com/user-attachments/assets/fd5e163b-b4fd-4e8b-86f2-1374cf233bdc)

**Comment by DonaldChung-HK** [comment]
Hi, I just forgot to put in the expose, it is fixed now. The switch deviation is just the `Local temperature calibration` endpoint.

I don't think the battery voltage is sent through zigbee so only the percentage is available.

**Comment by canope-25** [comment]
Hi , thank you for your help and reactivity !
Regarding the temp setting I mentioned , it's not the same setting:

This one is the local deviation :

![image](https://github.com/user-attachments/assets/ef7e6807-fdd8-4cfd-ac24-d2ea8e959cf0)

The other one is related to the eco mode and define hysteresis to us.
It's normally by 0.5 degre C but can be adapted in order to take account the local context :

![image](https://github.com/user-attachments/assets/db6d9c46-6741-4a14-8d2a-5ff10ffb6327) 

Thank you in advance for your help

**Comment by canope-25** [comment]
Hi ,

Hope you're well.

Have you seen my update ?

**Comment by canope-25** [comment]
> Hi, I just forgot to put in the expose, it is fixed now. The switch deviation is just the `Local temperature calibration` endpoint.
> 
> 
> 
> I don't think the battery voltage is sent through zigbee so only the percentage is available.

Hi,

I tested the new version .
Two info regarding that one :
- the two settings you added seems to not appear in zb2m ( 1.40.2 ) device settings.
![image](https://github.com/user-attachments/assets/c1f043d1-a0cd-4228-91b1-26974a9d665b)
![image](https://github.com/user-attachments/assets/bde90374-6540-4641-9615-406ba32b95dc)

Thank you in advance for your help
